require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PolcoGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # PolcoGroup. As you add validations to PolcoGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PolcoGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all polco_groups as @polco_groups" do
      polco_group = PolcoGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:polco_groups).should eq([polco_group])
    end
  end

  describe "GET show" do
    it "assigns the requested polco_group as @polco_group" do
      polco_group = PolcoGroup.create! valid_attributes
      get :show, {:id => polco_group.to_param}, valid_session
      assigns(:polco_group).should eq(polco_group)
    end
  end

  describe "GET new" do
    it "assigns a new polco_group as @polco_group" do
      get :new, {}, valid_session
      assigns(:polco_group).should be_a_new(PolcoGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested polco_group as @polco_group" do
      polco_group = PolcoGroup.create! valid_attributes
      get :edit, {:id => polco_group.to_param}, valid_session
      assigns(:polco_group).should eq(polco_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PolcoGroup" do
        expect {
          post :create, {:polco_group => valid_attributes}, valid_session
        }.to change(PolcoGroup, :count).by(1)
      end

      it "assigns a newly created polco_group as @polco_group" do
        post :create, {:polco_group => valid_attributes}, valid_session
        assigns(:polco_group).should be_a(PolcoGroup)
        assigns(:polco_group).should be_persisted
      end

      it "redirects to the created polco_group" do
        post :create, {:polco_group => valid_attributes}, valid_session
        response.should redirect_to(PolcoGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved polco_group as @polco_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        PolcoGroup.any_instance.stub(:save).and_return(false)
        post :create, {:polco_group => {}}, valid_session
        assigns(:polco_group).should be_a_new(PolcoGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PolcoGroup.any_instance.stub(:save).and_return(false)
        post :create, {:polco_group => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested polco_group" do
        polco_group = PolcoGroup.create! valid_attributes
        # Assuming there are no other polco_groups in the database, this
        # specifies that the PolcoGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PolcoGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => polco_group.to_param, :polco_group => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested polco_group as @polco_group" do
        polco_group = PolcoGroup.create! valid_attributes
        put :update, {:id => polco_group.to_param, :polco_group => valid_attributes}, valid_session
        assigns(:polco_group).should eq(polco_group)
      end

      it "redirects to the polco_group" do
        polco_group = PolcoGroup.create! valid_attributes
        put :update, {:id => polco_group.to_param, :polco_group => valid_attributes}, valid_session
        response.should redirect_to(polco_group)
      end
    end

    describe "with invalid params" do
      it "assigns the polco_group as @polco_group" do
        polco_group = PolcoGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PolcoGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => polco_group.to_param, :polco_group => {}}, valid_session
        assigns(:polco_group).should eq(polco_group)
      end

      it "re-renders the 'edit' template" do
        polco_group = PolcoGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PolcoGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => polco_group.to_param, :polco_group => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested polco_group" do
      polco_group = PolcoGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => polco_group.to_param}, valid_session
      }.to change(PolcoGroup, :count).by(-1)
    end

    it "redirects to the polco_groups list" do
      polco_group = PolcoGroup.create! valid_attributes
      delete :destroy, {:id => polco_group.to_param}, valid_session
      response.should redirect_to(polco_groups_url)
    end
  end

end
